#Ansible Module Name -- oss.py
#Test Case : create bucket with permission parameter Validation
#Ansible Playbook created by - Abha H
---
- name: create bucket with permission parameter Validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block:
     - name: Scenario 1 - create bucket with invalid permission parameter
       oss:
         access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeCreate }}'
         bucket: '{{ bucketName }}'
         permission: '{{ permissionInvalid }}'
         region: '{{ region }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 2 - create bucket with blank permission parameter
       oss:
         access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeCreate }}'
         bucket: '{{ bucketName }}'
         permission: 
         region: '{{ region }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
   - block:
     - name: Scenario 3 - create bucket with permission parameter as Permission
       oss:
         access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeCreate }}'
         bucket: '{{ bucketName }}'
         Permission: '{{ permission }}'
         region: '{{ region }}'
       register: result_scn3
     - debug: var=result_scn3
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       minutes: 1

   - block:
     - name: Scenario 4 - create bucket without permission parameter
       oss:
         access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeCreate }}'
         bucket: '{{ bucketName }}'
         region: '{{ region }}'
       register: result_scn4
     - debug: var=result_scn4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no        

   - pause:
       minutes: 1

   - block:
     - name: Scenario 4.1 - Delete bucket with all parameters
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeDelete }}'
         region: '{{ region }}'
         bucket: '{{ bucketName }}' 
       register: result_del_scn4
     - debug: var=result_del_scn4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
     always:
      - assert:
         that:
            - "'failed' in result_scn1"
            - "'value of permission must be one of: private,public-read,public-read-write, got: public' in result_scn1.msg"

            - "'failed' in result_scn2"
            - "'value of permission must be one of: private,public-read,public-read-write, got: None' in result_scn2.msg"

            - "'failed' in result_scn3"
            - "'unsupported parameter for module: Permission' in result_scn3.msg"

            - "'failed' not in result_scn4"
            
            - "'failed' not in result_del_scn4"

         msg: 'Test pass FAILED !!!'
        