#Ansible Module Name -- rds_acc_mgmt.py
#Test Case : Revoke Account permissions with all parameters
#Ansible Playbook created by - Abha H
---
- name: Revoke Account permissions with all parameters
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block :
     - name: Scenario 1 - create account
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         name: '{{ accName }}'
         password: '{{ accPwd }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn1
     - debug: var=result_scn1   

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause :
        seconds: 30

   - block:
     - name: Scenario 2 - create database
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ command }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
        db_description: '{{ dbDescription }}'
        character_set_name: '{{ characterSetName }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause :
        seconds: 30

   - block :
     - name: Scenario 3 - Grant account permissions
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: '{{ accountPriveledgeGrant }}'
       register: result_scn3
     - debug: var=result_scn3   

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - pause :
        seconds: 30

   - block :
     - name: Scenario 4 - Revoking account permissions
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandRevoke }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
       register: result_scn4
     - debug: var=result_scn4   

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - pause :
        seconds: 30
        
   - block :
      - name: Scenario 5 - delete account
        rds_acc_mgmt:
          acs_access_key: '{{ aliyun_acs_access_key }}'
          acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
          region: '{{ region }}'
          command: '{{ commandDelete }}'
          db_instance_id: '{{ instanceId }}'
          name: '{{ accName }}'  
        register: result_scn5
      - debug: var=result_scn5

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
        seconds: 30

   - block:
     - name: Scenario 6 - delete database
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandDelete }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
       register: result_scn6
     - debug: var=result_scn6
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
      
     always:
      - assert:  
         that:
            - "'failed' not in result_scn1"
            - "'failed' not in result_scn2"
            - "'failed' not in result_scn3"
            - "'failed' not in result_scn4"
            - "'failed' not in result_scn5"
            - "'failed' not in result_scn6"
         msg: 'Test pass FAILED !!!'
               
      