#Ansible Module Name -- rds_acc_mgmt.py
#Test Case : Grant account permissions with instance id parameter validation
#Ansible Playbook created by - Abha H
---
- name: Grant account with instance id parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block :
     - name: Scenario 1 - Grant account permissions with invalid instance id parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: '{{ instanceIdInvalid }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: '{{ accountPriveledgeGrant }}'
       register: result_scn1
     - debug: var=result_scn1 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 2 - Grant account permissions without instance id parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: '{{ accountPriveledgeGrant }}'
       register: result_scn2
     - debug: var=result_scn2 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 3 - Grant account permissions with blank instance id parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: 
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: '{{ accountPriveledgeGrant }}'
       register: result_scn3
     - debug: var=result_scn3

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 4 - Grant account permissions with command instance id as Instance id
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         Db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: '{{ accountPriveledgeGrant }}'
       register: result_scn4
     - debug: var=result_scn4 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
            - "'The specified instance is not found.' in result_scn1.msg[0]['Error Message']"
            
            - "'failed' in result_scn2"
            - "'db_instance_id is required for granting account permission' in result_scn2.msg"
            
            - "'failed' in result_scn3"
            - "'db_instance_id is required for granting account permission' in result_scn3.msg"
            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Db_instance_id' in result_scn4.msg"
            
         msg: 'Test pass FAILED !!!'