#Ansible Module Name -- rds.py
#Test Case : Create database with all parameters
#Ansible Playbook created by - Abha H
---
- name: Create database with all parameters
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - pause :
        seconds: 30
   - block:
     - name: Scenario 1 - create database
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ command }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
        db_description: '{{ dbDescription }}'
        character_set_name: '{{ characterSetName }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 2 - create database with same name
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ command }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
        db_description: '{{ dbDescription }}'
        character_set_name: '{{ characterSetName }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
        seconds: 30

   - block:
     - name: Scenario 3 - delete database
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandDelete }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
       register: result_scn3
     - debug: var=result_scn3
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "'failed' not in result_scn1"
            
            - "'failed' in result_scn2"
#            - "'The Security db Name is not in the available range or occupied.' in result_scn2.msg[0]['Error Message']"
            
            - "'failed' not in result_scn3"
            
         msg: 'Test pass FAILED !!!'
               
