#Ansible Module Name -- oss.py
#Test Case : Delete bucket with bucket parameter validation
#Ansible Playbook created by - Abha H
---
- name: Delete bucket with bucket parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block:
     - name: Senario1 - Delete bucket with bucket parameter having invalid value
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeDelete }}'
         bucket: '{{ invalidBucket }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 2 - Delete bucket with bucket param blank
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeDelete }}'
         bucket: 
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
   - block:
     - name: Scenario 3 - Delete bucket with bucket param as Bucket
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeDelete }}'
         Bucket: '{{ bucketNameWithLessThan3Chars }}'
         permission: '{{ permission }}'
         region: '{{ region }}'
       register: result_scn3
     - debug: var=result_scn3
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 4 - Delete bucket without bucket param
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeDelete }}'
         permission: '{{ permission }}'
         region: '{{ region }}'
       register: result_scn4
     - debug: var=result_scn4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no        

     always:
      - assert:
         that:
            - "'failed' in result_scn1"
#            - "'Error in deleting bucket Demo_Bucket. Details: {HostId: oss-cn-hangzhou.aliyuncs.com, Message: The specified bucket is not valid., Code: InvalidBucketName, RequestId: 58DB5050CE2B80171414FA35, BucketName: Demo_Bucket, }' in result_scn1.msg"

            - "'failed' in result_scn2"
            - "'bucket name is required' in result_scn2.msg"

            - "'failed' in result_scn3"
            - "'unsupported parameter for module: Bucket' in result_scn3.msg"

            - "'failed' in result_scn4"
            - "'missing required arguments: bucket' in result_scn4.msg"
                       
         msg: 'Test pass FAILED !!!'
        