# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for Volume parameter
# Playbook created by : Sachin J



- name: Validating volume parameter
  hosts: localhost
  connection: local


  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
    
     
  tasks:
  
#  Task: 1
  
  - block:
    - name: Validating - Volume parameter with valid volume count
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        #instance_type: '{{ instanceType }}'    Checking for Alias
        type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
        disks: '{{ disks }}'        # Alias
      register: create_instance_result_1
    - debug: var=create_instance_result_1

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15     

        
#  Task: 2    

  - block: 
    - name: Validating - Volume parameter with invalid volume count
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
        disks: '{{ invalidDisks }}'                    # Invalid volume count
      register: create_instance_result_2
    - debug: var=create_instance_result_2

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no

    always:
    - assert:
        that:
           - "'failed' not in create_instance_result_1"

           - "'failed' in create_instance_result_2"
           - "'more than four volumes or disk are not allowed.' in create_instance_result_2.msg"
        msg: 'Test pass FAILED !!!'
  - pause:
        seconds: 15     
   
  post_tasks:
   - name: Deleting newly created instance
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_1.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_1"

